Repository yagnik2411/Quiz-Genius, pull requests merged in 2024-10, with the labels that each got.

#30 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, level 1

#20 For now i've changed some Ui with text color of login and signup and …
  lib/pages/login_page.dart
  lib/pages/signUp_page.dart
  pubspec.lock
Labels: good first issue, gssoc-ext, level 1, hacktoberfest-accepted

#31 Added username in hamburger menu (Side Drawer)
  lib/pages/home_page.dart
Labels: gssoc-ext, level1, hacktoberfest-accepted

#44 Additon of All Contributors | Issue #40
  README.md
Labels: good first issue, gssoc-ext

#42 Add Image Upload Feature
  lib/firebase/auth.dart
  lib/main.dart
  lib/models/current_user.dart
  lib/pages/home_page.dart
  lib/pages/profile_page.dart
  lib/pages/signUp_page.dart
  lib/pages/username_page.dart
  lib/utils/colors.dart
  lib/utils/profile_image_service.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: gssoc-ext, level2, hacktoberfest-accepted

#64 Added issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation-update-issue-template.md
  .github/ISSUE_TEMPLATE/feature-improvement-issue-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc-ext, level2, hacktoberfest-accepted

#67 Add Workflow to close simillar issues
  .github/workflows/restrict.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#63 Add Github Greetings Bot and Auto Assign Labels
  .github/workflows/Auto-labels.yml
  .github/workflows/Greetings.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#78 Create LICENSE
  LICENSE
Labels: documentation, gssoc-ext, hacktoberfest

#82 display counter added
  lib/pages/quiz_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#35 #16 and #23 issue solved
  .vscode/settings.json
  android/app/build.gradle
  lib/firebase/auth.dart
  lib/main.dart
  lib/models/questions.dart
  lib/pages/home_page.dart
  lib/pages/quiz_mcq_page.dart
  lib/pages/quiz_page.dart
  lib/utils/my_route.dart
  pubspec.lock
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#98 oerflow resolved
  lib/pages/home_page.dart
Labels: gssoc-ext, level1, hacktoberfest-accepted

#94 Added #53
  lib/main.dart
  lib/models/questions.dart
  lib/pages/home_page.dart
  lib/pages/quiz_mcq_page.dart
  lib/pages/quiz_page.dart
  lib/utils/extensions.dart
Labels: gssoc-ext, level2, hacktoberfest-accepted

#102 Modified README.md file for project
  README.md
Labels: documentation, gssoc-ext, level1

#113 doc: Updated README.md
  README.md
  assets/images/gssocextd.jpg
  assets/images/hacktoberfest.png
Labels: documentation, gssoc-ext, level1, hacktoberfest-accepted

#83 Fix entity codes in question
  lib/pages/home_page.dart
  lib/pages/quiz_page.dart
  lib/utils/extensions.dart
  pubspec.yaml
Labels: bug, enhancement, gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#130 Add table with badges in README.md
  README.md
Labels: documentation, gssoc-ext, hacktoberfest

#114 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#134 Done the enhancements and also added some new sections
  CONTRIBUTING.md
Labels: documentation, gssoc-ext, level1, hacktoberfest

#139 forgot password functionality integrated and other issues resolved
  lib/pages/forgot_password.dart
  lib/pages/home_page.dart
  lib/pages/login_page.dart
  lib/pages/signUp_page.dart
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest
