Repository yagnik2411/Quiz-Genius, pull requests merged in 2024-11, with the labels that each got.

#148 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc-ext, level2, hacktoberfest

#145 Issue open/close message workflow automation🚀
  .github/workflows/issue-open-close.yml
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#151 PULL REQUEST MERGE WORKFLOW AUTOMATION🚀
  .github/workflows/pr-merge.yml
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#143 Replace MaterialStateProperty with WidgetStateProperty
  lib/main.dart
  lib/pages/forgot_password.dart
  lib/pages/quiz_page.dart
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#149 new quiz updated
  lib/pages/home_page.dart
Labels: bug, gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest

#157 Added Project Structure.md
  Project Structure.md
Labels: documentation, gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#127 Previous Score screen issue resolved
  lib/pages/quiz_page.dart
Labels: bug, gssoc-ext, level2, hacktoberfest

#135 dark light mode integratration done
  lib/main.dart
  lib/pages/home_page.dart
  lib/pages/login_page.dart
  lib/pages/previous_quiz_page.dart
  lib/pages/previous_scores_page.dart
  lib/pages/profile_page.dart
  lib/pages/quiz_mcq_page.dart
  lib/pages/quiz_page.dart
  lib/pages/signUp_page.dart
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted, hacktoberfest

#155 Create SECURITY.md
  SECURITY.md
Labels: documentation, gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest
